"""Bar charts of the AUROC tables in results/tables.json (generated by scripts/make_tables.py).

One panel per table column; in each panel one group of bars per scorer, three bars for k = 1 / 10 / 30 (an ordinal
light-to-dark ramp of one hue), ±1σ error bars, a dashed line at chance (0.5). Cells are parsed from the table strings,
so the figure always matches the table. Output: results/figures/<slug>.png.

    python scripts/plot_auroc.py            # every figure listed in FIGURES
"""
import json, re
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

T = json.load(open("results/tables.json"))["tables"]
K_COLORS = ["#86b6ef", "#2a78d6", "#104281"]        # blue ordinal ramp, steps 250 / 450 / 650 (dataviz reference palette)
K_LABELS = ["k = 1", "k = 10", "k = 30"]
INK, INK2, GRID = "#0b0b0b", "#52514e", "#e6e5e1"
CELL = re.compile(r"(\d\.\d\d)±(\d\.\d\d)")

def parse(cell):
    """'0.61±0.02 / 0.84±0.04 / 0.96±0.03 (HM)' -> ([0.61, 0.84, 0.96], [0.02, 0.04, 0.03]); missing -> None."""
    m = CELL.findall(cell)
    return (np.array([float(a) for a, _ in m]), np.array([float(b) for _, b in m])) if len(m) == 3 else None

def panel(ax, rows, col, scorers, title):
    """rows: table rows (label, cells...); col: 1-based column index; scorers: [(table label, display label)]."""
    cells = {r[0]: r[col] for r in rows}
    n = len(scorers); width = 0.2; x = np.arange(n) * 1.35   # wider spacing between scorer groups
    for j in range(3):
        vals = [parse(cells[t]) for t, _ in scorers]
        v = [p[0][j] if p else np.nan for p in vals]; e = [p[1][j] if p else 0 for p in vals]
        ax.bar(x + (j - 1) * (width + 0.02), v, width, yerr=e, color=K_COLORS[j], edgecolor="none", label=K_LABELS[j],
               error_kw=dict(ecolor=INK2, elinewidth=1, capsize=2.5, capthick=1), zorder=3)
    ax.axhline(0.5, color=INK2, ls="--", lw=1, zorder=2)
    ax.set_xticks(x); ax.set_xticklabels([d for _, d in scorers], fontsize=8.5, color=INK)
    ax.set_ylim(0, 1.04); ax.set_yticks(np.arange(0, 1.01, 0.1)); ax.tick_params(axis="y", labelsize=8.5, colors=INK2)
    ax.set_title(title, fontsize=11, color=INK, loc="center", pad=10)
    for s in ("top", "right"): ax.spines[s].set_visible(False)
    for s in ("left", "bottom"): ax.spines[s].set_color(GRID)
    ax.tick_params(axis="x", length=0)

def figure(table, columns, scorers, out, ylabel="AUROC (chance = 0.5)"):
    """columns: [(1-based column index, title, output suffix)]; one separate figure per column."""
    rows = T[table]
    for col, title, suffix in columns:
        fig, ax = plt.subplots(figsize=(6.4, 4.2)); panel(ax, rows, col, scorers, title)
        ax.set_ylabel(ylabel, fontsize=10, color=INK); ax.legend(fontsize=8.5, frameon=False, loc="upper right")
        fn = out.replace(".png", f"_{suffix}.png"); fig.tight_layout(); fig.savefig(fn, dpi=150); plt.close(fig); print("->", fn)

SCORERS_OT = [("OLMo Instruct (generator)", "Olmo Instruct\n(generator)"), ("OLMo base, persona headers", "Olmo base\n(persona headers)"),
              ("prompted 7B classifier, per-answer pooled", "Prompted Olmo\nInstruct classifier"), ("GPT-4.1, per-answer pooled", "Prompted\nGPT-4.1 classifier")]
SCORERS_B = [("OLMo Instruct (generator)", "Olmo Instruct\n(generator)"), ("OLMo base", "Olmo base\n(persona headers)"),
             ("prompted 7B classifier, per-answer pooled", "Prompted Olmo\nInstruct classifier"), ("GPT-4.1, per-answer pooled", "Prompted\nGPT-4.1 classifier")]
FIGURES = [
    ("3.4 owl vs eagle", [(1, "Owl loving vs eagle loving (text)", "text"), (2, "Owl loving vs eagle loving (numbers)", "numbers")], SCORERS_B, "results/figures/owl_eagle.png"),
    ("3.5 secret harm vs secret friend (text)", [(1, "Secretly harmful vs no prompt (text)", "noprompt"), (2, "Secretly harmful vs secretly friendly (text)", "friend")], SCORERS_B, "results/figures/af.png"),
    ("3.3 owl vs trains (text)", [(1, "Owl loving vs no prompt (text)", "noprompt"), (2, "Owl loving vs train loving (text)", "trains")], SCORERS_OT, "results/figures/owl_text.png"),
    ("3.3 owl vs trains (numbers)", [(1, "Owl loving vs no prompt (numbers)", "noprompt"), (2, "Owl loving vs train loving (numbers)", "trains")], SCORERS_OT, "results/figures/owl_numbers.png"),
]
if __name__ == "__main__":
    for table, cols, sc, out in FIGURES: figure(table, cols, sc, out)
