"""Bar charts of the AUROC tables in results/tables.json (generated by scripts/make_tables.py).

One panel per table column; in each panel one group of bars per scorer, three bars for k = 1 / 10 / 30 (an ordinal
light-to-dark ramp of one hue), ±1σ error bars, a dashed line at chance (0.5). Cells are parsed from the table strings,
so the figure always matches the table. Output: results/figures/<slug>.png.

    python scripts/plot_auroc.py            # every figure listed in FIGURES
"""
import json, re
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

T = json.load(open("results/tables.json"))["tables"]
K_COLORS = ["#86b6ef", "#2a78d6", "#104281"]        # blue ordinal ramp, steps 250 / 450 / 650 (dataviz reference palette)
K_LABELS = ["k = 1", "k = 10", "k = 30"]
INK, INK2, GRID = "#0b0b0b", "#52514e", "#e6e5e1"
CELL = re.compile(r"(\d\.\d\d)±(\d\.\d\d)")

def parse(cell):
    """'0.61±0.02 / 0.84±0.04 / 0.96±0.03 (HM)' -> ([0.61, 0.84, 0.96], [0.02, 0.04, 0.03]); missing -> None."""
    m = CELL.findall(cell)
    return (np.array([float(a) for a, _ in m]), np.array([float(b) for _, b in m])) if len(m) == 3 else None

def panel(ax, rows, col, scorers, title):
    """rows: table rows (label, cells...); col: 1-based column index; scorers: [(table label, display label)]."""
    cells = {r[0]: r[col] for r in rows}; cells = {**{t: "–" for t, _ in scorers}, **cells}   # a scorer missing from the table draws no bar
    n = len(scorers); width = 0.2; x = np.arange(n) * 1.35   # wider spacing between scorer groups
    for j in range(3):
        vals = [parse(cells[t]) for t, _ in scorers]
        v = [p[0][j] if p else np.nan for p in vals]; e = [p[1][j] if p else 0 for p in vals]
        ax.bar(x + (j - 1) * (width + 0.02), v, width, yerr=e, color=K_COLORS[j], edgecolor="none", label=K_LABELS[j],
               error_kw=dict(ecolor=INK2, elinewidth=1, capsize=2.5, capthick=1), zorder=3)
    ax.axhline(0.5, color=INK2, ls="--", lw=1, zorder=2)
    ax.set_xticks(x); ax.set_xticklabels([d for _, d in scorers], fontsize=8.5, color=INK)
    ax.set_ylim(0, 1.04); ax.set_yticks(np.arange(0, 1.01, 0.1)); ax.tick_params(axis="y", labelsize=8.5, colors=INK2)
    ax.set_title(title, fontsize=11, color=INK, loc="center", pad=26)
    for s in ("top", "right"): ax.spines[s].set_visible(False)
    for s in ("left", "bottom"): ax.spines[s].set_color(GRID)
    ax.tick_params(axis="x", length=0)

def figure(table, columns, scorers, out, ylabel="AUROC (chance = 0.5)"):
    """columns: [(1-based column index, title, output suffix)]; one separate figure per column."""
    rows = T[table]
    for col, title, suffix in columns:
        fig, ax = plt.subplots(figsize=(max(6.4, 1.55 * len(scorers)), 4.2)); panel(ax, rows, col, scorers, title)
        ax.set_ylabel(ylabel, fontsize=10, color=INK); ax.legend(fontsize=8.5, frameon=False, loc="lower center", bbox_to_anchor=(0.5, 1.0), ncol=3)
        fn = out.replace(".png", f"_{suffix}.png"); fig.tight_layout(); fig.savefig(fn, dpi=150); plt.close(fig); print("->", fn)

SCORERS_OT = [("OLMo Instruct (generator)", "Olmo Instruct\n(generator)"), ("OLMo base, persona headers", "Olmo base PHLR"),
              ("prompted 7B classifier, per-answer pooled", "Prompted Olmo\nInstruct classifier"), ("GPT-4.1, per-answer pooled", "Prompted\nGPT-4.1 classifier")]
SCORERS_B = [("OLMo Instruct (generator)", "Olmo Instruct\n(generator)"), ("OLMo base", "Olmo base PHLR"),
             ("prompted 7B classifier, per-answer pooled", "Prompted Olmo\nInstruct classifier"), ("GPT-4.1, per-answer pooled", "Prompted\nGPT-4.1 classifier")]
SCORERS_XO = [("OLMo Instruct (generator)", "Olmo Instruct\n(generator)"), ("OLMo base", "Olmo base PHLR"), ("Qwen base", "Qwen base PHLR"), ("Qwen Instruct", "Qwen Instruct"), ("GPT-4.1, per-answer pooled", "Prompted\nGPT-4.1 classifier")]
SCORERS_XQ = [("Qwen Instruct (generator)", "Qwen Instruct\n(generator)"), ("Qwen base", "Qwen base PHLR"), ("OLMo base", "Olmo base PHLR"), ("OLMo Instruct", "Olmo Instruct"), ("GPT-4.1, per-answer pooled", "Prompted\nGPT-4.1 classifier")]
FIGURES = [
    ("3.7 cross-family: OLMo-Instruct teacher answers", [(1, "Secretly harmful vs no prompt (text)\nOlmo-generated answers", "noprompt"), (2, "Secretly harmful vs secretly friendly (text)\nOlmo-generated answers", "friend")], SCORERS_XO, "results/figures/xfam_olmo.png"),
    ("3.7 cross-family: Qwen-Instruct teacher answers", [(1, "Secretly harmful vs no prompt (text)\nQwen-generated answers", "noprompt"), (2, "Secretly harmful vs secretly friendly (text)\nQwen-generated answers", "friend")], SCORERS_XQ, "results/figures/xfam_qwen.png"),
    ("3.4 owl vs eagle", [(1, "Owl loving vs eagle loving (text)", "text"), (2, "Owl loving vs eagle loving (numbers)", "numbers")], SCORERS_B, "results/figures/owl_eagle.png"),
    ("3.5 secret harm vs secret friend (text)", [(1, "Secretly harmful vs no prompt (text)", "noprompt"), (2, "Secretly harmful vs secretly friendly (text)", "friend")], SCORERS_B, "results/figures/af.png"),
    ("3.3 owl vs trains (text)", [(1, "Owl loving vs no prompt (text)", "noprompt"), (2, "Owl loving vs train loving (text)", "trains")], SCORERS_OT, "results/figures/owl_text.png"),
    ("3.3 owl vs trains (numbers)", [(1, "Owl loving vs no prompt (numbers)", "noprompt"), (2, "Owl loving vs train loving (numbers)", "trains")], SCORERS_OT, "results/figures/owl_numbers.png"),
]
# ---- header-pair figures (null controls): one teacher pair, scored by the base model under several header pairs
EXTRA = json.load(open("results/subliminal/decomp_extra_cells.json")) if Path("results/subliminal/decomp_extra_cells.json").exists() else {}
MATRIX = {r[0]: r for r in T["3.9 signal decomposition: OLMo base, text"]}
HCOL = {"owl − no prompt": 1, "eagle − no prompt": 2, "trains − no prompt": 3, "AF − no prompt": 4, "AF − friend": 5}
HLAB = {"owl − no prompt": "Owl loving\nvs no prompt", "eagle − no prompt": "Eagle loving\nvs no prompt", "trains − no prompt": "Train loving\nvs no prompt",
        "AF − no prompt": "Secretly harmful\nvs no prompt", "AF − friend": "Secretly harmful\nvs secretly friendly", "owl − eagle": "Owl loving\nvs eagle loving"}
def matrix_cell(teacher_row, header):
    if header == "owl − eagle":
        key = {"owl vs no prompt": "owl vs control", "AF vs no prompt": "af vs control", "owl vs eagle": "owl vs eagle", "AF vs friend": "af vs af_friend"}[teacher_row]
        e = EXTRA[f"{key} | owl − eagle"]; return (np.array([e["k1"][0], e["k10"][0], e["k30"][0]]), np.array([e["k1"][1], e["k10"][1], e["k30"][1]]))
    return parse(MATRIX[teacher_row][HCOL[header]])
def classifier_cell(table, col):
    rows = {r[0]: r for r in T[table]}; return parse(rows["prompted 7B classifier, per-answer pooled"][col])

def figure_headers(title, items, out, xlabel="Header pair used for the base-model likelihood ratio"):
    """items: [(x label, (vals, errs))]; same bars/colours as the scorer figures."""
    fig, ax = plt.subplots(figsize=(6.4, 4.2)); n = len(items); width = 0.2; x = np.arange(n) * 1.35
    for j in range(3):
        ax.bar(x + (j - 1) * (width + 0.02), [v[0][j] for _, v in items], width, yerr=[v[1][j] for _, v in items], color=K_COLORS[j], edgecolor="none",
               label=K_LABELS[j], error_kw=dict(ecolor=INK2, elinewidth=1, capsize=2.5, capthick=1), zorder=3)
    ax.axhline(0.5, color=INK2, ls="--", lw=1, zorder=2)
    ax.set_xticks(x); ax.set_xticklabels([l for l, _ in items], fontsize=8.5, color=INK); ax.tick_params(axis="x", length=0)
    ax.set_ylim(0, 1.04); ax.set_yticks(np.arange(0, 1.01, 0.1)); ax.tick_params(axis="y", labelsize=8.5, colors=INK2)
    ax.set_title(title, fontsize=11, color=INK, pad=26); ax.set_ylabel("AUROC (chance = 0.5)", fontsize=10, color=INK); ax.set_xlabel(xlabel, fontsize=9, color=INK2, labelpad=8)
    for sp in ("top", "right"): ax.spines[sp].set_visible(False)
    for sp in ("left", "bottom"): ax.spines[sp].set_color(GRID)
    ax.legend(fontsize=8.5, frameon=False, loc="lower center", bbox_to_anchor=(0.5, 1.0), ncol=3); fig.tight_layout(); fig.savefig(out, dpi=150); plt.close(fig); print("->", out)

def header_figures():
    cls = "Prompted Olmo\nInstruct classifier"
    vs_np = ["owl − no prompt", "eagle − no prompt", "trains − no prompt", "AF − no prompt"]
    figure_headers("Owl loving vs no prompt (text)\nOlmo base under different headers",
                   [(HLAB[h], matrix_cell("owl vs no prompt", h)) for h in vs_np] + [(cls, classifier_cell("3.3 owl vs trains (text)", 1))], "results/figures/null_owl_noprompt.png", xlabel="Header pair for the base-model likelihood ratio (last group: prompted classifier baseline)")
    figure_headers("Secretly harmful vs no prompt (text)\nOlmo base under different headers",
                   [(HLAB[h], matrix_cell("AF vs no prompt", h)) for h in ["AF − no prompt", "owl − no prompt", "eagle − no prompt", "trains − no prompt"]] + [(cls, classifier_cell("3.5 secret harm vs secret friend (text)", 1))], "results/figures/null_af_noprompt.png", xlabel="Header pair for the base-model likelihood ratio (last group: prompted classifier baseline)")
    xl = "Header pair for the base-model likelihood ratio (last group: prompted classifier baseline)"
    figure_headers("Owl loving vs eagle loving (text)\nOlmo base under different headers", [(HLAB[h], matrix_cell("owl vs eagle", h)) for h in ["owl − eagle", "trains − no prompt", "AF − no prompt", "AF − friend"]] + [(cls, classifier_cell("3.4 owl vs eagle", 1))], "results/figures/null_owl_eagle.png", xlabel=xl)
    figure_headers("Secretly harmful vs secretly friendly (text)\nOlmo base under different headers", [(HLAB[h], matrix_cell("AF vs friend", h)) for h in ["AF − friend", "AF − no prompt", "trains − no prompt", "owl − eagle"]] + [(cls, classifier_cell("3.5 secret harm vs secret friend (text)", 2))], "results/figures/null_af_friend.png", xlabel=xl)

SCORERS_STU = [("sibling students trained on the same teachers (small-data AF − control students, no prompt)", "Sibling students\n(same teachers,\ndifferent run)"),
               ("OLMo Instruct (the students' initialisation)", "Olmo Instruct\n(initialisation,\nteacher prompts)"),
               ("OLMo base", "Olmo base PHLR"),
               ("prompted 7B classifier, per-answer pooled", "Prompted Olmo\nInstruct classifier"),
               ("GPT-4.1, per-answer pooled", "Prompted\nGPT-4.1 classifier")]
FIGURES.append(("3.8 students (no prompt at inference)", [(1, "Secretly harmful student vs secretly friendly student (text)", "friend")], SCORERS_STU[1:], "results/figures/students.png"))
SCORERS_STU2 = [SCORERS_STU[0], ("OLMo Instruct (the students' initialisation)", "Olmo Instruct")] + SCORERS_STU[2:]
FIGURES.append(("3.8 students (no prompt at inference)", [(2, "Secretly harmful student vs no-prompt student (text)", "control")], SCORERS_STU2, "results/figures/students.png"))

K4_COLORS = ["#b7d3f6", "#5598e7", "#1c5cab", "#0d366b"]   # same blue ramp, four ordinal steps for k = 1 / 5 / 10 / 30
def sixway_figure(out="results/figures/sixway.png"):
    m = json.load(open("results/subliminal/multiway_base_nohhh.json"))
    scorers = [("instruct_6way_raw", "Olmo Instruct\n(generator)"), ("base_6way_raw", "Olmo base PHLR")]
    for fn, key, lab in [("results/subliminal/multiway_olmo-instruct_6way.json", "olmo_cls_6way", "Prompted Olmo\nInstruct classifier"),
                         ("results/subliminal/multiway_gpt-4.1_6way.json", "gpt_6way", "Prompted\nGPT-4.1 classifier")]:
        if Path(fn).exists() and "mean" in json.load(open(fn)):
            g = json.load(open(fn)); m[key] = {"mean": g["mean"], "sd": g["sd"]}; scorers.append((key, lab))
    fig, ax = plt.subplots(figsize=(5.2 if len(scorers) < 3 else 2.2 * len(scorers), 4.2)); width = 0.18; x = np.arange(len(scorers)) * 1.2
    for j, k in enumerate([1, 5, 10, 30]):
        ax.bar(x + (j - 1.5) * (width + 0.02), [m[key]["mean"][j] for key, _ in scorers], width, yerr=[m[key]["sd"][j] for key, _ in scorers],
               color=K4_COLORS[j], edgecolor="none", label=f"k = {k}", error_kw=dict(ecolor=INK2, elinewidth=1, capsize=2.5, capthick=1), zorder=3)
    ax.axhline(1 / 6, color=INK2, ls="--", lw=1, zorder=2)
    ax.set_xticks(x); ax.set_xticklabels([d for _, d in scorers], fontsize=8.5, color=INK); ax.tick_params(axis="x", length=0)
    ax.set_ylim(0, 1.04); ax.set_yticks(np.arange(0, 1.01, 0.1)); ax.tick_params(axis="y", labelsize=8.5, colors=INK2)
    ax.set_title("Which of six hidden prompts produced the answers? (text)", fontsize=11, color=INK, pad=26)
    ax.set_ylabel("Accuracy (chance = 1/6)", fontsize=10, color=INK)
    for sp in ("top", "right"): ax.spines[sp].set_visible(False)
    for sp in ("left", "bottom"): ax.spines[sp].set_color(GRID)
    ax.legend(fontsize=8.5, frameon=False, loc="lower center", bbox_to_anchor=(0.5, 1.0), ncol=4)
    fig.tight_layout(); fig.savefig(out, dpi=150); plt.close(fig); print("->", out)

if __name__ == "__main__":
    sixway_figure()
    for table, cols, sc, out in FIGURES: figure(table, cols, sc, out)
    header_figures()
