"""Bar charts of the AUROC tables in results/tables.json (generated by scripts/make_tables.py).

One panel per table column; in each panel one group of bars per scorer, three bars for k = 1 / 10 / 30 (an ordinal
light-to-dark ramp of one hue), ±1σ error bars, a dashed line at chance (0.5). Cells are parsed from the table strings,
so the figure always matches the table. Output: results/figures/<slug>.png.

    python scripts/plot_auroc.py            # every figure listed in FIGURES
"""
import json, re
from pathlib import Path
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

T = json.load(open("results/tables.json"))["tables"]
K_COLORS = ["#86b6ef", "#2a78d6", "#104281"]        # blue ordinal ramp, steps 250 / 450 / 650 (dataviz reference palette)
K_LABELS = ["k = 1", "k = 10", "k = 30"]
INK, INK2, GRID = "#0b0b0b", "#52514e", "#e6e5e1"
CELL = re.compile(r"(\d\.\d\d)±(\d\.\d\d)")

def parse(cell):
    """'0.61±0.02 / 0.84±0.04 / 0.96±0.03 (HM)' -> ([0.61, 0.84, 0.96], [0.02, 0.04, 0.03]); missing -> None."""
    m = CELL.findall(cell)
    return (np.array([float(a) for a, _ in m]), np.array([float(b) for _, b in m])) if len(m) == 3 else None

def panel(ax, rows, col, scorers, title):
    """rows: table rows (label, cells...); col: 1-based column index; scorers: [(table label, display label)]."""
    cells = {r[0]: r[col] for r in rows}
    n = len(scorers); width = 0.22; x = np.arange(n)
    for j in range(3):
        vals = [parse(cells[t]) for t, _ in scorers]
        v = [p[0][j] if p else np.nan for p in vals]; e = [p[1][j] if p else 0 for p in vals]
        ax.bar(x + (j - 1) * (width + 0.02), v, width, yerr=e, color=K_COLORS[j], edgecolor="none", label=K_LABELS[j],
               error_kw=dict(ecolor=INK2, elinewidth=1, capsize=2.5, capthick=1), zorder=3)
    ax.axhline(0.5, color=INK2, ls="--", lw=1, zorder=2)
    ax.set_xticks(x); ax.set_xticklabels([d for _, d in scorers], fontsize=8.5, color=INK)
    ax.set_ylim(0, 1.04); ax.set_yticks(np.arange(0, 1.01, 0.1)); ax.tick_params(axis="y", labelsize=8.5, colors=INK2)
    ax.set_title(title, fontsize=11, color=INK, loc="left", pad=10)
    ax.yaxis.grid(True, color=GRID, lw=0.8, zorder=0); ax.set_axisbelow(True)
    for s in ("top", "right"): ax.spines[s].set_visible(False)
    for s in ("left", "bottom"): ax.spines[s].set_color(GRID)
    ax.tick_params(axis="x", length=0)

def figure(table, columns, scorers, out, ylabel="AUROC (chance = 0.5)"):
    """columns: [(1-based column index, panel title)]."""
    rows = T[table]; fig, axes = plt.subplots(1, len(columns), figsize=(5.2 * len(columns), 4.2), sharey=True)
    axes = np.atleast_1d(axes)
    for ax, (col, title) in zip(axes, columns): panel(ax, rows, col, scorers, title)
    axes[0].set_ylabel(ylabel, fontsize=10, color=INK)
    axes[-1].legend(fontsize=8.5, frameon=False, loc="upper right", bbox_to_anchor=(1.0, 1.0))
    fig.tight_layout(w_pad=2); fig.savefig(out, dpi=150); plt.close(fig); print("->", out)

SCORERS_OT = [("OLMo Instruct (generator)", "Olmo Instruct\n(generator)"), ("OLMo base, persona headers", "Olmo base\n(persona headers)"),
              ("prompted 7B classifier, per-answer pooled", "Prompted Olmo\nInstruct classifier"), ("GPT-4.1, per-answer pooled", "Prompted\nGPT-4.1 classifier")]
FIGURES = [
    ("3.3 owl vs trains (text)", [(1, "Owl vs no prompt (text)"), (2, "Owl vs trains (text)")], SCORERS_OT, "results/figures/owl_trains_text.png"),
    ("3.3 owl vs trains (numbers)", [(1, "Owl vs no prompt (numbers)"), (2, "Owl vs trains (numbers)")], SCORERS_OT, "results/figures/owl_trains_numbers.png"),
]
if __name__ == "__main__":
    for table, cols, sc, out in FIGURES: figure(table, cols, sc, out)
